ConsumeWebApi/ConsumeWebApi/Models/CommentViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ConsumeWebApi.Models
{
    public class CommentViewModel
    {
        public int PostId { get; set; }

        [Required]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }

        public string Body { get; set; }

    }
}

ConsumeWebApi/ConsumeWebApi/Models/ErrorViewModel.cs
namespace ConsumeWebApi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConsumeWebApi/ConsumeWebApi/Controllers/CommentController.cs
using ConsumeWebApi.Models;
using ConsumeWebApi.Pagination;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ConsumeWebApi.Controllers
{
    public class CommentController : Controller
    {
        
        Uri baseAddress = new Uri("https://jsonplaceholder.typicode.com/comments");
        private readonly HttpClient _httpClient;

        public CommentController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }
        [HttpGet]
        public IActionResult Index(int? pageNumber, int? pageSize)
        {
            List<CommentViewModel> commentsList = new List<CommentViewModel>();
            HttpResponseMessage response = _httpClient.GetAsync(_httpClient.BaseAddress).Result;

            if(response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                commentsList = JsonConvert.DeserializeObject<List<CommentViewModel>>(data);
            }

            int defaultPageSize = 10;
            int currentPageNumber = pageNumber ?? 1;
            int currentPageSize = pageSize ?? defaultPageSize;

            var paginatedComments = PaginatedList<CommentViewModel>.Create(commentsList, currentPageNumber, currentPageSize);
            ViewBag.PageSize = currentPageSize;

            return View(paginatedComments);
        }
    }
}

ConsumeWebApi/ConsumeWebApi/Controllers/HomeController.cs
using ConsumeWebApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsumeWebApi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsumeWebApi/ConsumeWebApi/Views/Comment/Index.cshtml
@model ConsumeWebApi.Pagination.PaginatedList<CommentViewModel>

@{
    ViewData["Title"] = "Comments Paging";
}

<h1>Comments Paging</h1>

<table class="table">
    <thead>
        <tr>
            <th class="visually-hidden">@Html.DisplayName("Post ID") </th>
            <th> @Html.DisplayName("ID")  </th>
            <th> @Html.DisplayName("Name") </th>
            <th>@Html.DisplayName("Email")</th>
            <th> @Html.DisplayName("Body") </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td class="visually-hidden">@Html.DisplayFor(modelItem => item.PostId)</td>
            <td> @Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Name) </td>
            <td> @Html.DisplayFor(modelItem => item.Email)  </td>
            <td> @Html.DisplayFor(modelItem => item.Body) </td>
        </tr>
}
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPrevious ? "disabled" : "";
    var nextDisabled = !Model.HasNext ? "disabled" : "";

    var startPage = Math.Max(1, Model.PageIndex - 2);
    var endPage = Math.Min(Model.TotalPages, Model.PageIndex + 2);

    var currentPageSize = ViewBag.PageSize ?? 10;
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="pagination">
                <nav aria-label="Page navigation comments">
                    <ul class="pagination">
                        <li class="page-item @prevDisabled"><a asp-action="Index" asp-route-pageNumber="1" asp-route-pageSize="@currentPageSize" class="page-link">First</a></li>
                        <li class="page-item @prevDisabled"><a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)" asp-route-pageSize="@currentPageSize" class="page-link">Previous</a></li>

                        @if (startPage > 1)
                        {
                            <li class="page-item"><a asp-action="Index" asp-route-pageNumber="1" asp-route-pageSize="@currentPageSize" class="page-link">1</a></li>
                            @if (startPage > 2)
                            {
                                <li class="page-item disabled"><span class="page-link">...</span></li>
                            }
                        }

                        @for (int i = startPage; i <= endPage; i++)
                        {
                            var active = i == Model.PageIndex ? "active" : "";
                            <li class="page-item @active"><a asp-action="Index" asp-route-pageNumber="@i" asp-route-pageSize="@currentPageSize" class="page-link">@i</a></li>
                        }

                        @if (endPage < Model.TotalPages)
                        {
                            @if (endPage < Model.TotalPages - 1)
                            {
                                <li class="page-item disabled"><span class="page-link">...</span></li>
                            }
                            <li class="page-item"><a asp-action="Index" asp-route-pageNumber="@Model.TotalPages" asp-route-pageSize="@currentPageSize" class="page-link">@Model.TotalPages</a></li>
                        }

                        <li class="page-item @nextDisabled"><a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)" asp-route-pageSize="@currentPageSize" class="page-link">Next</a></li>
                        <li class="page-item @nextDisabled"><a asp-action="Index" asp-route-pageNumber="@Model.TotalPages" asp-route-pageSize="@currentPageSize" class="page-link">Last</a></li>
                    </ul>
                </nav>
            </div>
             <div class="page-size-form">
                <form asp-action="Index" method="get">
                    <label for="pageSize">Page Size </label>
                    <select id="pageSize" name="pageSize">
                        <option value="10">10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                    </select>
                    <script>
                        document.getElementById("pageSize").value = @ViewBag.PageSize;
                    </script>
                    <button type="submit" class="btn btn-default btn-sm">Apply</button>
                </form>
            </div>
        </div>

        <div class="col-md-6" style ="text-align:right">
            <span class="total-data-info">Total Record(s) : @(currentPageSize * (Model.TotalPages - 1) + Model.Count) Row(s)</span>
        </div>
    </div>
</div>

ConsumeWebApi/ConsumeWebApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ConsumeWebApi/ConsumeWebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConsumeWebApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsumeWebApi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ConsumeWebApi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comment">Comment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ConsumeWebApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>